apiVersion: v1
kind: Service
metadata:
  name: wbo-service
  labels:
    app: wbo
spec:
  type: NodePort
  selector:
    app: wbo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001  # You can change the nodePort if needed
 
